version: '3.8'

services:
  manager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: manager-io
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./manager_data:/data:cached
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - manager_network
    security_opt:
      - no-new-privileges:true
    read_only: false
    environment:
      - TZ=UTC

networks:
  manager_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
    driver_opts:
      com.docker.network.bridge.name: manager-net
    attachable: true

volumes:
  manager_data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/manager_data
      o: bind
